name: Test FreeBSD VM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Pull Docker image
        run: docker pull aygpdr/freebsd:latest
      
      - name: Test Alpine container layer
        run: |
          echo "Testing container OS..."
          docker run --rm aygpdr/freebsd:latest cat /etc/os-release | grep -i alpine
          
          echo "Testing QEMU availability..."
          docker run --rm aygpdr/freebsd:latest which qemu-system-x86_64
      
      - name: Start FreeBSD container
        run: |
          docker run -d --name freebsd-test --privileged \
            -p 2222:22 \
            aygpdr/freebsd:latest
          
          echo "Waiting for container to start..."
          sleep 5
          docker ps | grep freebsd-test
      
      - name: Check QEMU process
        run: |
          docker exec freebsd-test pgrep qemu-system || \
            echo "QEMU not yet started"
          
          docker logs freebsd-test
      
      - name: Wait for FreeBSD boot
        run: |
          echo "Waiting for FreeBSD VM to boot (60 seconds max)..."
          timeout=60
          while [ $timeout -gt 0 ]; do
            if docker exec freebsd-test nc -z localhost 22 2>/dev/null; then
              echo "FreeBSD SSH port is open!"
              break
            fi
            echo "Waiting... ($timeout seconds left)"
            sleep 10
            timeout=$((timeout - 10))
          done
      
      - name: Test FreeBSD access
        run: |
          # Install sshpass for automated testing
          sudo apt-get update && sudo apt-get install -y sshpass
          
          # Test SSH connection to FreeBSD
          sshpass -p 'freebsd' ssh -o StrictHostKeyChecking=no \
            -p 2222 root@localhost 'uname -a' || \
            echo "FreeBSD not accessible via SSH yet"
      
      - name: Container logs
        if: always()
        run: docker logs freebsd-test
      
      - name: Cleanup
        if: always()
        run: |
          docker stop freebsd-test || true
          docker rm freebsd-test || true
